"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory$git_branch$git_status$python$nodejs$character"""

right_format = """$time"""

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bold cyan"
format = "[$path ]($style)"

[git_branch]
symbol = ""
style = "bold purple"
format = "[$symbol$branch ]($style)"

[git_status]
style = "bold yellow"
format = "[($all_status$ahead_behind) ]($style)"

[python]
symbol = ""
style = "bold green"
format = "[${symbol}${version} ]($style)"

[nodejs]
symbol = ""
style = "bold green"
format = "[${symbol}${version} ]($style)"

[character]
success_symbol = "[›](bold green)"
error_symbol = "[›](bold red)"

[time]
disabled = false
time_format = "%H:%M"
style = "dimmed white"
format = "[$time]($style)"
